web:
  build: .
  volumes: &app_volumes
    - .:/app
    - ~/.ssh:/root/.ssh
    - ~/.bash_history:/root/.bash_history
  volumes_from:
    - bundle_cache
  ports:
    - 3000:3000
  links: &app_links
    - db
    - redis
  env_file:
    - web.env
  dns:
    - 10.50.1.10
    - 8.8.8.8

db:
  image: postgres:9.6

redis:
  image: redis

bundle_cache:
  image: busybox
  volumes:
    - /bundle_cache
